### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/TrackedDistributions.jl#3]

**Comment by nickrobinson251** [comment]
should be closed after https://github.com/JuliaRegistries/General/pull/4589

**Comment by iamed2** [comment]
IMO we should register 1.0.0, which is what the internal package was at

**Comment by nickrobinson251** [comment]
> IMO we should register 1.0.0, which is what the internal package was at

good call #4 

will update Registry PR after that :)

**Comment by nickrobinson251** [comment]
https://github.com/JuliaRegistries/General/pull/4591

**Comment by nicoleepp** [comment]
Can this be closed?
